"""
PDF service — loads pre-compiled .txt files from a Google Drive folder.

Workflow:
  1. Run `scripts/compile_lp_docs.py` locally whenever source PDFs change.
     It downloads the raw PDFs, extracts their text, and uploads .txt files
     back to the same Drive folder.
  2. This service loads those .txt files at server startup (eager, background).
     Loading plain text is 10-20x faster than parsing raw PDFs with pdfplumber.

The folder is set via FUND2_DRIVE_FOLDER_ID env var.
"""

import io
from typing import Optional

from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

from config.settings import settings
from src.utils.logger import get_logger

logger = get_logger(__name__)

_SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]


class PDFService:
    def __init__(self):
        self._cached_text: Optional[str] = None
        self._cached_deck: Optional[str] = None

    def _drive(self):
        credentials = Credentials.from_service_account_file(
            settings.google_credentials_file, scopes=_SCOPES
        )
        return build("drive", "v3", credentials=credentials, cache_discovery=False)

    def get_document_context(self) -> Optional[str]:
        """
        Load pre-compiled .txt files from the configured Drive folder and return
        their content as a single string. Result is cached for the server session.

        The .txt files are generated by scripts/compile_lp_docs.py — run that
        script locally whenever the source PDFs change.
        """
        if self._cached_text is not None:
            return self._cached_text

        if not settings.fund2_drive_folder_id:
            logger.warning("FUND2_DRIVE_FOLDER_ID is not set — LP chat has no documents")
            return None

        try:
            drive = self._drive()
            results = drive.files().list(
                q=(
                    f"'{settings.fund2_drive_folder_id}' in parents"
                    " and mimeType='text/plain'"
                    " and trashed=false"
                ),
                fields="files(id, name)",
                orderBy="name",
            ).execute()
        except Exception as e:
            logger.error("Failed to list Drive folder", error=str(e))
            return None

        files = results.get("files", [])
        if not files:
            logger.warning(
                "No .txt files found in Drive folder — run scripts/compile_lp_docs.py first",
                folder_id=settings.fund2_drive_folder_id,
            )
            return None

        # Put the Fundraising Deck first — it's the primary source of truth
        files.sort(key=lambda f: (0 if "fundraising deck" in f["name"].lower() else 1, f["name"]))

        texts = []
        for file in files:
            try:
                request = drive.files().get_media(fileId=file["id"])
                fh = io.BytesIO()
                downloader = MediaIoBaseDownload(fh, request)
                done = False
                while not done:
                    _, done = downloader.next_chunk()
                fh.seek(0)
                texts.append(fh.read().decode("utf-8"))
                logger.info("Loaded text file from Drive", file=file["name"])
            except Exception as e:
                logger.error("Failed to load text file", file=file["name"], error=str(e))

        if not texts:
            return None

        self._cached_text = "\n\n".join(texts)
        logger.info("LP doc context ready", files=len(texts), chars=len(self._cached_text))
        return self._cached_text

    def get_deck_context(self) -> Optional[str]:
        """
        Load only the Fundraising Deck .txt file from Drive and return its text.
        Result is cached for the server session.
        """
        if self._cached_deck is not None:
            return self._cached_deck

        if not settings.fund2_drive_folder_id:
            logger.warning("FUND2_DRIVE_FOLDER_ID is not set — deck not available")
            return None

        try:
            drive = self._drive()
            results = drive.files().list(
                q=(
                    f"'{settings.fund2_drive_folder_id}' in parents"
                    " and mimeType='text/plain'"
                    " and trashed=false"
                ),
                fields="files(id, name)",
            ).execute()
        except Exception as e:
            logger.error("Failed to list Drive folder for deck", error=str(e))
            return None

        deck_file = next(
            (f for f in results.get("files", []) if "fundraising deck" in f["name"].lower()),
            None,
        )
        if not deck_file:
            logger.warning("Fundraising Deck .txt not found in Drive folder")
            return None

        try:
            request = drive.files().get_media(fileId=deck_file["id"])
            fh = io.BytesIO()
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while not done:
                _, done = downloader.next_chunk()
            fh.seek(0)
            self._cached_deck = fh.read().decode("utf-8")
            logger.info("Fundraising Deck loaded from Drive", chars=len(self._cached_deck))
            return self._cached_deck
        except Exception as e:
            logger.error("Failed to load Fundraising Deck", error=str(e))
            return None


pdf_service = PDFService()
